### ISSUE TITLE
Cumulus should tell you when passing string instead of array to "depends"

### ISSUE THREAD

**Issue by radeksimko** [cotdsa/cumulus#20]
Following template:

```yaml
default:
  region: eu-west-1
  stacks:
    networking:
      cf_template: networking.json
      depends:
    computing:
      cf_template: computing.json
      depends: networking
```

end up in really unhelpful error:

```
CRITICAL:cumulus.MegaStack:Could not resolve dependancy order. Either circular dependancy or dependancy on stack not in yaml file.
```

It took me almost an hour to find out that `depends` expects an array, not a string, which is why I think that cumulus should first check what's being passed from the YAML template (string or array) and then show helpful error if it's a string.

btw. _dependancy_ is spelled as **dependency** in modern english. http://en.wiktionary.org/wiki/dependancy
