### ISSUE TITLE
VpcId required when creating Instance.

### ISSUE THREAD

**Issue by baelish** [cotdsa/cumulus#32]
Hello, relatively new at this so please let me know if I've the wrong end of the stick.

When creating a new Instance I noticed that a VpcId is required

```
{"Error":{"Code":"ValidationError","Message":"Parameters: [VpcId] must have values","Type":"Sender"},"RequestId":"d6dca9e2-eaa0-11e4-a596-15ee2d514b72"}
```

However it's not even mentioned in the [AWS Cloud formation reference](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html) as a valid property. Is there another reason why cumulus is asking for the vpc id?

Secondly I found that judging by my JSON file output section:
```
    "Outputs": {
### truncated ###
        "VpcId": {
            "Description": "VpcId of the created VPC",
            "Value": {
                "Ref": "Dorne"
            }
        }
    },
```

I should be able to get the vpc id by putting the following in the yaml:
```
                VpcId:
                    source: HdVpcInSydney
                    type: output
                    variable: Dorne
```
However it only works if I put the following instead:
```
                VpcId:
                    source: HdVpcInSydney
                    type: output
                    variable: VpcId
```

Thanks, workaround available so not urgent.
